import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
const source=fs.readFileSync(new URL('./index.ts',import.meta.url),'utf8').replace(/^import .*$/m,'').replace('export async function','async function').replace("'1408989746'","'777'");let handler;
const context={Deno:{env:{get:()=>''},serve:f=>handler=f},crypto:webcrypto,TextEncoder,TextDecoder,atob,Response,fetch:()=>{throw Error('Unexpected network')}};vm.createContext(context);vm.runInContext(source,context);
const keys=await webcrypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const jwk=await webcrypto.subtle.exportKey('jwk',keys.publicKey);jwk.kid='key1';jwk.alg='RS256';
const now=10000;const claims={iss:'https://token.actions.githubusercontent.com',aud:'ysk-dev-publisher',iat:now,nbf:now,exp:now+300,repository:'Krussedull86/YSK-Kjorestudio',repository_id:'777',repository_owner_id:'231093498',ref:'refs/heads/dev',sub:'repo:Krussedull86@231093498/YSK-Kjorestudio@777:ref:refs/heads/dev',workflow_ref:'Krussedull86/YSK-Kjorestudio/.github/workflows/dev.yml@refs/heads/dev',event_name:'push'};
const encode=v=>Buffer.from(JSON.stringify(v)).toString('base64url');
async function token(c=claims,alg='RS256'){const raw=encode({alg,kid:'key1'})+'.'+encode(c);const sig=await webcrypto.subtle.sign('RSASSA-PKCS1-v1_5',keys.privateKey,new TextEncoder().encode(raw));return raw+'.'+Buffer.from(sig).toString('base64url');}
const fetchKeys=async()=>new Response(JSON.stringify({keys:[jwk]}));await context.authorize(await token(),fetchKeys,now);
for(const extra of [{aud:'wrong'},{iss:'https://attacker.test'},{repository_id:'778'},{repository_owner_id:'42'},{ref:'refs/heads/main'},{sub:'repo:Krussedull86/YSK-Kjorestudio:ref:refs/heads/dev'},{workflow_ref:'attacker.yml'},{event_name:'pull_request'},{exp:now-1},{nbf:now+100},{iat:now-700}]){const jwt=await token({...claims,...extra});await assert.rejects(()=>context.authorize(jwt,fetchKeys,now));}
const jwt=await token();await assert.rejects(()=>context.authorize(jwt.slice(0,-10)+'a'.repeat(10),fetchKeys,now));const wrongAlg=await token(claims,'none');await assert.rejects(()=>context.authorize(wrongAlg,fetchKeys,now));console.log('OIDC signature, issuer, immutable subject, repo, workflow, branch, event and lifetime checks passed.');
