package no.talappen.ysk;
import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import android.text.InputType;import org.json.*;import java.util.*;import java.text.SimpleDateFormat;
public class MainActivity extends Activity {
 final int BG=Color.rgb(11,20,35),PANEL=Color.rgb(20,34,56),TEAL=Color.rgb(73,216,189),TEXT=Color.rgb(237,244,255),MUTED=Color.rgb(153,171,195);
 final String[] QUAL={"trafikksikkerhet","avpassing","økning","komfort"};LinearLayout body;TextView status;Map<String,EditText> inputs=new HashMap<>();Map<String,String> ratings=new HashMap<>();int trip=1;String editId=null;JSONObject managedEdit=null;List<JSONObject> managed=new ArrayList<>();String manageKind="Turer";long lastSync=0;boolean syncing=false,adminBusy=false,authenticated=false,checkingLogin=false;TripDb db;Handler timer=new Handler(Looper.getMainLooper());String page="";Updates updates;ParamTrips paramTrips;Button updateButton;ScrollView scroll;TripTimer tripClock=new TripTimer();TextView clockView;Button clockStart,clockStop;long seenStopsVersion=0;boolean updatingStops=false;
 Runnable tick=new Runnable(){public void run(){updateStatus();if(authenticated)updates.automatic();if(authenticated&&System.currentTimeMillis()-lastSync>30000&&!getSharedPreferences("cloud",0).getString("url","").isEmpty())sync();timer.postDelayed(this,5000);}};
 final List<AlertDialog> dialogs=new ArrayList<>();
 AlertDialog.Builder dialog(){return new AlertDialog.Builder(this){public AlertDialog show(){AlertDialog d=super.show();dialogs.add(d);d.setOnDismissListener(x->dialogs.remove(d));return d;}};}
 void dismissDialogs(){for(AlertDialog d:new ArrayList<>(dialogs))d.dismiss();}
 final String[] TRIP_NAMES={"Optimaltur 1","Optimaltur 2","Optimaltur 3","Transportoppdrag 1 (distribusjon)","Transportoppdrag 2 (langtur)"};LinearLayout tripChoices;
 String tripName(int n){return n>=1&&n<=5?TRIP_NAMES[n-1]:"Tur "+n;}
 int activeTrips(String course){try{JSONArray rows=new JSONArray(getSharedPreferences("cloud",0).getString("course_setup","[]"));for(int i=0;i<rows.length();i++)if(rows.getJSONObject(i).getString("name").equals(course.trim()))return rows.getJSONObject(i).getInt("active_trips");}catch(Exception ignored){}return 5;}
 void paintTrips(){if(tripChoices==null||!page.equals("form"))return;tripChoices.removeAllViews();int count=activeTrips(inputs.get("course").getText().toString());for(int n=1;n<=5;n++){if(n>count&&!(editId!=null&&n==trip))continue;final int selected=n;button(tripChoices,tripName(n)+(n>count?" (tidligere tur)":""),()->{if(tripClock.running&&selected!=trip){alert("Stopp tidtakingen før du bytter tur.");return;}if(distributionRun!=null&&selected!=trip){alert("Nullstill distribusjonsloggen eller velg Ny tur før du bytter tur.");return;}trip=selected;paintTrips();persistDraft();},n==trip);}paintDistribution();}
 void courseSetup(String course){if(!requireLogin())return;LinearLayout panel=new LinearLayout(this);panel.setOrientation(1);EditText input=setupField(panel,"Kursnavn",course,false);Spinner count=new Spinner(this);count.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"1 aktiv tur","2 aktive turer","3 aktive turer","4 aktive turer","5 aktive turer"}));count.setSelection(activeTrips(course)-1);panel.addView(count);JSONObject old=courseDistribution(course);EditText stops=setupField(panel,"Antall distribusjonsstopp (0–30; 0 = av)",old==null?"0":old.optString("stop_count","0"),true);EditText total=setupField(panel,"Forventet totaltid skole → skole (minutter)",old==null?"0":old.optString("expected_minutes","0"),true);ScrollView view=new ScrollView(this);view.addView(panel);dialog().setTitle("Kursoppsett").setView(view).setNegativeButton("Avbryt",null).setPositiveButton("Lagre",(d,w)->{try{int n=Integer.parseInt(stops.getText().toString().trim());double t=Double.parseDouble(total.getText().toString().trim().replace(',','.'));double[] values=DistributionRun.validatePlan(n,t,new double[0]);JSONObject plan=new JSONObject().put("stop_count",n).put("expected_minutes",t).put("deadlines",new JSONArray(values));manageAction(new JSONObject().put("action","course_setup_save").put("name",input.getText().toString().trim()).put("active_trips",count.getSelectedItemPosition()+1).put("distribution_plan",plan));}catch(Exception e){alert(e.getMessage());}}).show();}
 EditText setupField(LinearLayout panel,String label,String value,boolean number){TextView title=new TextView(this);title.setText(label);panel.addView(title);EditText input=new EditText(this);input.setText(value);if(number)input.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);panel.addView(input);return input;}
 DistributionRun distributionRun;LinearLayout distributionHost;TextView distributionLive;View regularClock;
 JSONObject courseDistribution(String course){try{JSONArray rows=new JSONArray(getSharedPreferences("cloud",0).getString("course_setup","[]"));for(int i=0;i<rows.length();i++){JSONObject row=rows.getJSONObject(i);if(row.getString("name").equals(course.trim()))return row.optJSONObject("distribution_plan");}}catch(Exception ignored){}return null;}
 double[] deadlineArray(JSONArray a)throws Exception{double[] d=new double[a==null?0:a.length()];for(int i=0;i<d.length;i++)d[i]=a.getDouble(i);return d;}
 JSONObject distributionJson(boolean clock)throws Exception{return distributionRun==null?null:DistributionState.write(distributionRun,clock);}
 void restoreDistribution(JSONObject d)throws Exception{distributionRun=DistributionState.read(d);}
 long seenDistributionVersion=0;
 void refreshDistribution(){if(!page.equals("form")||!inputs.containsKey("minutes"))return;android.content.SharedPreferences p=getSharedPreferences("draft",0);long version=p.getLong("distribution_version",0);if(version==seenDistributionVersion)return;try{JSONObject d=new JSONObject(p.getString("payload","{}"));restoreDistribution(d.optJSONObject("distribution"));seenDistributionVersion=version;if(distributionRun!=null&&distributionRun.finishedMillis>=0)inputs.get("minutes").setText(String.format(Locale.ROOT,"%.4f",distributionRun.finishedMillis/60000.0));paintDistribution();}catch(Exception e){alert(e.getMessage());}}
 void menuDistribution(int action){continueForm();if(!page.equals("form")||distributionRun==null||distributionRun.finishedMillis>=0)return;if(action==9)requestFinishDistribution();else if(distributionRun.events.size()<distributionRun.deadlines.length){if(action==7)recordRamp();else abortDistributionStop();}}
 void freezeDistribution(){if(!page.equals("form"))return;for(String k:new String[]{"driver","course","vehicle","minutes","date","start_time"})if(inputs.containsKey(k))inputs.get(k).setEnabled(distributionRun==null);}
 void startDistribution(){try{if(tripClock.running)throw new Exception("Stopp den andre tidtakingen først.");for(String k:new String[]{"driver","course","vehicle"})if(inputs.get(k).getText().toString().trim().isEmpty())throw new Exception("Velg sjåfør, kurs og bil før Start.");JSONObject p=courseDistribution(inputs.get("course").getText().toString());if(p==null||p.optInt("stop_count")==0)throw new Exception("Admin må angi stopp og forventet tid i kursoppsettet først.");TimerService.dismiss(this);tripClock.reset();persistClock();long now=System.currentTimeMillis();distributionRun=new DistributionRun(p.getDouble("expected_minutes"),deadlineArray(p.getJSONArray("deadlines")),now,SystemClock.elapsedRealtime(),boot());inputs.get("date").setText(new SimpleDateFormat("yyyy-MM-dd",Locale.ROOT).format(new Date(now)));inputs.get("start_time").setText(new SimpleDateFormat("HH:mm",Locale.ROOT).format(new Date(now)));freezeDistribution();persistDraft();paintDistribution();notificationTimer();}catch(Exception e){alert(e.getMessage());}}
 void markDistribution(String state,String reason){try{refreshDistribution();distributionRun.mark(state,reason,SystemClock.elapsedRealtime(),System.currentTimeMillis(),boot());persistDraft();paintDistribution();if(TimerService.active)TimerService.show(this,"show");}catch(Exception e){alert(e.getMessage());}}
 void recordRamp(){refreshDistribution();if(distributionRun==null||distributionRun.finishedMillis>=0||distributionRun.events.size()>=distributionRun.deadlines.length)return;int stop=distributionRun.events.size()+1;markDistribution("ramp","");if(distributionRun.events.size()>=stop)commentDistribution(stop);}
 void commentDistribution(int stop){refreshDistribution();if(distributionRun==null||stop>distributionRun.events.size())return;final long start=distributionRun.startedWall;EditText note=new EditText(this);note.setHint("Kommentar til rampe/stopp (valgfritt, maks 300 tegn)");note.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);note.setText(distributionRun.events.get(stop-1).reason);dialog().setTitle("Kommentar · stopp "+stop).setView(note).setNegativeButton("Lukk",null).setPositiveButton("Lagre kommentar",(d,w)->{try{refreshDistribution();if(distributionRun==null||distributionRun.startedWall!=start)throw new Exception("Turen er endret.");distributionRun.comment(stop,note.getText().toString().trim());persistDraft();paintDistribution();}catch(Exception e){alert(e.getMessage());}}).show();}
 void requestFinishDistribution(){dialog().setTitle("Avslutt tur ved skolen?").setMessage("Avslutt først når bilen er tilbake ved skolen. Returen inngår i totaltiden fra skole til skole.").setNegativeButton("Fortsett retur",null).setPositiveButton("Tilbake ved skolen",(d,w)->finishDistribution()).show();}
 void abortDistributionStop(){final int expected=distributionRun.events.size()+1;EditText reason=new EditText(this);reason.setHint("Grunn (valgfritt, maks 300 tegn)");dialog().setTitle("Avbryt stopp "+(distributionRun.events.size()+1)+"?").setView(reason).setNegativeButton("Tilbake",null).setPositiveButton("Merk avbrutt",(d,w)->{refreshDistribution();if(distributionRun!=null&&distributionRun.events.size()+1==expected)markDistribution("aborted",reason.getText().toString().trim());else alert("Stoppet er allerede registrert. Åpne neste stopp.");}).show();}
 void finishDistribution(){try{refreshDistribution();TimerService.dismiss(this);distributionRun.finish(SystemClock.elapsedRealtime(),System.currentTimeMillis(),boot());inputs.get("minutes").setText(String.format(Locale.ROOT,"%.4f",distributionRun.finishedMillis/60000.0));persistDraft();paintDistribution();}catch(Exception e){alert(e.getMessage());}}
 String stopLine(DistributionRun.Event e,long prior){double total=e.elapsedMillis/60000.0;return String.format(Locale.getDefault(),"Stopp %d · %s\nFra forrige: %.1f min · Fra start: %.1f min%s",e.stop,e.status.equals("ramp")?"Rygget til rampe":"AVBRUTT",(e.elapsedMillis-prior)/60000.0,total,e.reason.isEmpty()?"":"\nKommentar: "+e.reason);}
 void paintDistributionClock(){if(!page.equals("form")||trip!=4||distributionRun==null||distributionLive==null)return;DistributionRun r=distributionRun;double actual=r.elapsed(SystemClock.elapsedRealtime(),System.currentTimeMillis(),boot())/60000.0;String line=String.format(Locale.getDefault(),"%s · %.1f min fra start\nForventet skole → skole: %.1f min",r.finishedMillis>=0?"Avsluttet":"Pågår",actual,r.expectedMinutes);if(r.finishedMillis<0&&r.events.size()<r.deadlines.length)line+="\nNeste: stopp "+(r.events.size()+1);if(r.events.size()==r.deadlines.length)line+=String.format(Locale.getDefault(),"\n%s · siste stopp → skole: %.1f min",r.finishedMillis>=0?"Retur registrert":"Retur pågår",r.returnMillis(SystemClock.elapsedRealtime(),System.currentTimeMillis(),boot())/60000.0);if(r.finishedMillis<0)line+="\n"+r.remainingText(Math.round(actual*60000));distributionLive.setText(line);}
 void paintDistribution(){if(!page.equals("form"))return;JSONObject config=inputs.containsKey("course")?courseDistribution(inputs.get("course").getText().toString()):null;boolean delivery=trip==4&&(distributionRun!=null||config!=null&&config.optInt("stop_count")>0);if(regularClock!=null)regularClock.setVisibility(delivery?View.GONE:View.VISIBLE);if(distributionHost==null)return;distributionHost.setVisibility(trip==4?View.VISIBLE:View.GONE);distributionHost.removeAllViews();distributionLive=null;if(trip!=4)return;distributionHost.addView(text("DISTRIBUSJON · LEVERINGSSTOPP",17,TEAL));distributionHost.addView(text("Start ved skolen. Avslutt når bilen er tilbake ved skolen. Tiden inkluderer lasting, venting, pauser og retur. Leveringsstopp telles separat fra unødige stopp.",13,MUTED));if(distributionRun==null){JSONObject p=courseDistribution(inputs.get("course").getText().toString());int n=p==null?0:p.optInt("stop_count");distributionHost.addView(text(n==0?"Ingen stoppplan. Admin kan sette den i Kursoppsett.":n+" stopp · forventet totalt "+p.optDouble("expected_minutes")+" min",16,TEXT));button(distributionHost,"Start distribusjonsoppdrag",()->startDistribution(),true);return;}distributionLive=text("",18,TEAL);distributionHost.addView(distributionLive);paintDistributionClock();long prior=0;for(DistributionRun.Event e:distributionRun.events){distributionHost.addView(text(stopLine(e,prior),15,e.status.equals("aborted")?Color.rgb(255,138,149):TEXT));final int stop=e.stop;button(distributionHost,"Kommentar til stopp "+stop,()->commentDistribution(stop),false);prior=e.elapsedMillis;}if(distributionRun.finishedMillis<0){if(distributionRun.events.size()<distributionRun.deadlines.length){int n=distributionRun.events.size()+1;button(distributionHost,"Stopp "+n+": Rygget til rampe",()->recordRamp(),true);button(distributionHost,"Avbryt stopp "+n+" …",()->abortDistributionStop(),false);}else button(distributionHost,"Tilbake ved skolen: Avslutt tur",()->requestFinishDistribution(),true);}button(distributionHost,"Nullstill distribusjonslogg …",()->dialog().setTitle("Nullstill distribusjonslogg?").setMessage("Starttid og alle registrerte leveringsstopp slettes fra dette utkastet.").setNegativeButton("Avbryt",null).setPositiveButton("Nullstill",(d,w)->{refreshDistribution();TimerService.dismiss(this);distributionRun=null;freezeDistribution();persistDraft();paintDistribution();}).show(),false);freezeDistribution();}
 Spinner feedbackType;String feedbackId;
 void persistFeedback(){if(!page.equals("feedback")||!inputs.containsKey("feedback_body"))return;try{getSharedPreferences("feedback",0).edit().putString("draft",new JSONObject().put("id",feedbackId).put("kind",feedbackType.getSelectedItemPosition()).put("title",inputs.get("feedback_title").getText().toString()).put("body",inputs.get("feedback_body").getText().toString()).toString()).commit();}catch(Exception ignored){}}
 void feedbackEnabled(boolean enabled){if(!page.equals("feedback"))return;for(String key:new String[]{"feedback_title","feedback_body"})if(inputs.containsKey(key))inputs.get(key).setEnabled(enabled);if(feedbackType!=null)feedbackType.setEnabled(enabled);}
 interface FeedbackResult {void accept(JSONObject result)throws Exception;}
 void feedbackRequest(JSONObject request,FeedbackResult callback){if(!requireLogin()||adminBusy)return;adminBusy=true;feedbackEnabled(false);status.setText("Oppdaterer tilbakemelding …");new Thread(()->{try{JSONObject result=Sync.admin(this,request);runOnUiThread(()->{adminBusy=false;feedbackEnabled(true);if(isDestroyed()||!authenticated)return;try{callback.accept(result);}catch(Exception e){alert(e.getMessage());}});}catch(Exception e){runOnUiThread(()->{adminBusy=false;feedbackEnabled(true);if(!isDestroyed()&&authenticated)alert(e.getMessage());});}},"YSK-feedback").start();}
 void feedbackForm(){if(!requireLogin())return;persistDraft();persistFeedback();page="feedback";clockView=null;body.removeAllViews();inputs.clear();JSONObject d=new JSONObject();try{d=new JSONObject(getSharedPreferences("feedback",0).getString("draft","{}"));}catch(Exception ignored){}feedbackId=d.optString("id",UUID.randomUUID().toString());body.addView(text("Tilbakemelding",23,TEXT));feedbackType=new Spinner(this);feedbackType.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Tilbakemelding / forslag","Feilmelding"}));feedbackType.setSelection(d.optInt("kind",0));body.addView(feedbackType);field("feedback_title","Tittel (maks 120 tegn)",d.optString("title"),false,false);EditText message=field("feedback_body","Beskriv forslaget eller feilen (maks 4000 tegn)",d.optString("body"),false,false);message.setSingleLine(false);message.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);message.setMinLines(5);body.addView(text("Navn, appversjon, telefonmodell og Android-versjon følger med. Lagres i skolens adminpanel; videresendes til Discord hvis konfigurert. Utkastet beholdes ved nettfeil.",13,MUTED));button(body,"Send tilbakemelding",()->sendFeedback(),true);persistFeedback();}
 void sendFeedback(){if(adminBusy)return;persistFeedback();try{String title=inputs.get("feedback_title").getText().toString().trim(),message=inputs.get("feedback_body").getText().toString().trim();if(title.isEmpty()||title.length()>120||message.isEmpty()||message.length()>4000)throw new Exception("Tittel: 1–120 tegn. Melding: 1–4000 tegn.");android.content.pm.PackageInfo info=getPackageManager().getPackageInfo(getPackageName(),0);JSONObject request=new JSONObject().put("action","feedback_submit").put("id",feedbackId).put("kind",feedbackType.getSelectedItemPosition()==0?"suggestion":"bug").put("title",title).put("body",message).put("platform","android").put("version",info.versionName+" / B"+updates.installed()).put("device",Build.MANUFACTURER+" "+Build.MODEL+" · Android "+Build.VERSION.RELEASE);feedbackRequest(request,result->{getSharedPreferences("feedback",0).edit().clear().commit();if(page.equals("feedback")){page="";feedbackForm();}Toast.makeText(this,result.optString("message"),Toast.LENGTH_LONG).show();});}catch(Exception e){alert(e.getMessage());}}
 AlertDialog feedbackInboxDialog;
 String feedbackStatus(String value){return value.equals("open")?"Ny":value.equals("working")?"Under behandling":"Ferdig";}
 String feedbackDelivery(String value){switch(value){case "sent":return "Sendt";case "failed":return "Feilet";case "off":return "Ikke konfigurert";case "sending":return "Sender";default:return "Venter";}}
 int feedbackOffset=0;
 void feedbackInbox(){try{feedbackRequest(new JSONObject().put("action","feedback_list").put("offset",feedbackOffset),result->{LinearLayout panel=new LinearLayout(this);panel.setOrientation(1);JSONArray rows=result.getJSONArray("rows");for(int i=0;i<rows.length();i++){JSONObject row=rows.getJSONObject(i);panel.addView(text((row.optString("kind").equals("bug")?"FEIL":"FORSLAG")+" · "+row.optString("title"),18,TEXT));panel.addView(text(row.optString("author")+" · "+row.optString("platform")+" "+row.optString("version")+"\nStatus: "+feedbackStatus(row.optString("status"))+" · Discord: "+feedbackDelivery(row.optString("delivery")),13,MUTED));button(panel,"Les melding",()->dialog().setTitle(row.optString("title")).setMessage(row.optString("body")+"\n\nEnhet: "+row.optString("device")+"\n"+row.optString("delivery_error")).setPositiveButton("Lukk",null).show(),false);LinearLayout states=new LinearLayout(this);panel.addView(states);String[] keys={"open","working","resolved"},labels={"Ny","Behandles","Ferdig"};for(int j=0;j<keys.length;j++){final String key=keys[j];button(states,labels[j],()->feedbackChange(row.optString("id"),"feedback_status",key),false);}button(panel,"Prøv Discord på nytt",()->feedbackChange(row.optString("id"),"feedback_retry",null),false);}if(rows.length()==0)panel.addView(text("Ingen meldinger på denne siden.",16,TEXT));button(panel,"Discord · to webhooks",()->feedbackHooks(),true);LinearLayout pages=new LinearLayout(this);panel.addView(pages);button(pages,"← Forrige",()->{feedbackOffset=Math.max(0,feedbackOffset-100);feedbackInbox();},false);button(pages,"Neste →",()->{feedbackOffset+=100;feedbackInbox();},false);ScrollView view=new ScrollView(this);view.addView(panel);if(feedbackInboxDialog!=null)feedbackInboxDialog.dismiss();feedbackInboxDialog=dialog().setTitle("Admin · Tilbakemeldinger").setView(view).setPositiveButton("Lukk",null).show();});}catch(Exception e){alert(e.getMessage());}}
 void feedbackChange(String id,String action,String value){try{JSONObject request=new JSONObject().put("action",action).put("id",id);if(value!=null)request.put("status",value);feedbackRequest(request,r->{Toast.makeText(this,r.optString("message"),Toast.LENGTH_LONG).show();if(feedbackInboxDialog!=null&&feedbackInboxDialog.isShowing())feedbackInbox();});}catch(Exception e){alert(e.getMessage());}}
 void feedbackHooks(){try{feedbackRequest(new JSONObject().put("action","feedback_hooks_get"),result->{LinearLayout panel=new LinearLayout(this);panel.setOrientation(1);Map<String,EditText> urls=new HashMap<>();Map<String,CheckBox> disable=new HashMap<>();JSONArray hooks=result.getJSONArray("hooks");for(int i=0;i<hooks.length();i++){JSONObject hook=hooks.getJSONObject(i);String key=hook.getString("kind");panel.addView(text((key.equals("bug")?"Feilmelding":"Tilbakemelding / forslag")+(hook.getBoolean("enabled")?" · konfigurert":" · ikke konfigurert"),16,TEXT));EditText input=new EditText(this);input.setHint("Lim inn ny Discord-webhook");input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);panel.addView(input);urls.put(key,input);CheckBox off=new CheckBox(this);off.setText("Deaktiver webhook");off.setTextColor(TEXT);panel.addView(off);disable.put(key,off);}panel.addView(text("Tomt felt beholder eksisterende webhook.",13,MUTED));dialog().setTitle("Discord-webhooks · egen skole").setView(panel).setNegativeButton("Avbryt",null).setPositiveButton("Lagre",(d,w)->{if(adminBusy)return;adminBusy=true;Map<String,String> changes=new HashMap<>();for(String key:urls.keySet())if(disable.get(key).isChecked()||!urls.get(key).getText().toString().trim().isEmpty())changes.put(key,disable.get(key).isChecked()?"":urls.get(key).getText().toString().trim());new Thread(()->{try{for(Map.Entry<String,String> e:changes.entrySet())Sync.admin(this,new JSONObject().put("action","feedback_hooks_save").put("kind",e.getKey()).put("url",e.getValue()));runOnUiThread(()->{adminBusy=false;if(authenticated)Toast.makeText(this,"Webhook-innstillinger lagret",Toast.LENGTH_LONG).show();});}catch(Exception e){runOnUiThread(()->{adminBusy=false;if(authenticated)alert(e.getMessage());});}},"YSK-feedback-hooks").start();}).show();});}catch(Exception e){alert(e.getMessage());}}
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);db=new TripDb(this);updates=new Updates(this);paramTrips=new ParamTrips(this);
  LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(BG);root.setPadding(dp(18),dp(12),dp(18),dp(12));setContentView(root);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(dp(18),dp(12)+insets.getSystemWindowInsetTop(),dp(18),dp(12)+insets.getSystemWindowInsetBottom());return insets;});
  LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);root.addView(bar);TextView brand=text("YSK Kjørestudio",18,TEXT);brand.setTypeface(null,Typeface.BOLD);bar.addView(brand,new LinearLayout.LayoutParams(0,dp(44),1));Button menu=new Button(this);menu.setText("☰");menu.setTextColor(TEAL);menu.setTextSize(24);menu.setBackgroundColor(Color.TRANSPARENT);menu.setContentDescription("Åpne meny");bar.addView(menu,new LinearLayout.LayoutParams(dp(52),dp(48)));menu.setOnClickListener(v->navigation(menu));
  scroll=new ScrollView(this);scroll.setFillViewport(true);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout content=new LinearLayout(this);content.setOrientation(1);scroll.addView(content);status=text("Lagrer på telefonen · også uten nett",12,MUTED);content.addView(status);body=new LinearLayout(this);body.setOrientation(1);content.addView(body);updateButton=new Button(this);restoreClock();
  TimerService.dismiss(this);settings();resumeSession();

 }
 public void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);persistDraft();if(page.equals("form"))try{out.putString("draft",draft().toString());}catch(Exception ignored){}}
 public void onRequestPermissionsResult(int code,String[] permissions,int[] results){super.onRequestPermissionsResult(code,permissions,results);if(code==42&&results.length>0&&results[0]==android.content.pm.PackageManager.PERMISSION_GRANTED)TimerService.show(this,"show");}
 public void onResume(){super.onResume();restoreClock();timer.removeCallbacks(clockTick);timer.post(clockTick);timer.post(tick);updateStatus();if(authenticated)updates.automatic();}
 public void onPause(){if(paramTrips!=null)paramTrips.persist();persistFeedback();persistDraft();super.onPause();timer.removeCallbacks(tick);timer.removeCallbacks(clockTick);}
 public void onDestroy(){dismissDialogs();timer.removeCallbacks(clockTick);timer.removeCallbacks(tick);db.close();super.onDestroy();}
 int boot(){return android.provider.Settings.Global.getInt(getContentResolver(),android.provider.Settings.Global.BOOT_COUNT,0);}
 long clockMillis(){return tripClock.elapsed(SystemClock.elapsedRealtime(),System.currentTimeMillis(),boot());}
 void restoreClock(){tripClock=TimerService.load(this);}
 void persistClock(){TimerService.store(this,tripClock);}
 void notificationTimer(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},42);TimerService.show(this,"show");}
 JSONObject draft()throws Exception{JSONObject d=new JSONObject();for(Map.Entry<String,EditText> e:inputs.entrySet())d.put(e.getKey(),e.getValue().getText().toString());for(String k:QUAL)d.put(k,ratings.get(k));d.put("trip",trip);if(editId!=null)d.put("id",editId);if(managedEdit!=null)d.put("_managed",managedEdit);if(distributionRun!=null)d.put("distribution",distributionJson(true));return d;}
 void persistDraft(){if(!page.equals("form"))return;try{refreshDistribution();refreshStops();getSharedPreferences("draft",0).edit().putString("payload",draft().toString()).commit();}catch(Exception ignored){}}
 void refreshStops(){if(!page.equals("form")||!inputs.containsKey("stops"))return;android.content.SharedPreferences p=getSharedPreferences("draft",0);long version=p.getLong("stops_version",0);if(version==seenStopsVersion)return;try{JSONObject d=new JSONObject(p.getString("payload","{}"));updatingStops=true;inputs.get("stops").setText(d.optString("stops","0"));seenStopsVersion=version;}catch(Exception ignored){}finally{updatingStops=false;}}
 void manualStops(){if(updatingStops||!page.equals("form"))return;android.content.SharedPreferences p=getSharedPreferences("draft",0);seenStopsVersion=p.getLong("stops_version",0)+1;p.edit().putLong("stops_version",seenStopsVersion).commit();persistDraft();if(TimerService.active)TimerService.show(this,"show");}
 void addStop(){try{refreshStops();inputs.get("stops").setText(String.valueOf(StopCounter.next(inputs.get("stops").getText().toString())));}catch(Exception e){alert(e.getMessage());}}
 void clearDraft(){distributionRun=null;TimerService.dismiss(this);getSharedPreferences("trip_clock",0).edit().remove("completed").commit();page="";getSharedPreferences("draft",0).edit().clear().commit();tripClock.reset();persistClock();}
 void continueForm(){if(!requireLogin())return;persistFeedback();persistDraft();try{String raw=getSharedPreferences("draft",0).getString("payload","");form(raw.isEmpty()?null:new JSONObject(raw));}catch(Exception e){alert(e.getMessage());}}
 void newTrip(){if(!requireLogin())return;if(tripClock.running||!getSharedPreferences("draft",0).getString("payload","").isEmpty())dialog().setTitle("Ny tur?").setMessage("Avslutte utkastet og nullstille tidtakingen? Velg Fortsett tur i menyen for å beholde det.").setNegativeButton("Avbryt",null).setPositiveButton("Ny tur",(d,w)->{clearDraft();form(null);}).show();else{clearDraft();form(null);}}
 void navigation(View anchor){if(!requireLogin())return;persistFeedback();persistDraft();PopupMenu menu=new PopupMenu(this,anchor);String[] labels={"Fortsett tur","Ny tur","Mine turer","Turer, kurs og biler","Innstillinger","Synkroniser nå","Sjekk oppdateringer"};for(int i=0;i<labels.length;i++)menu.getMenu().add(0,i,i,labels[i]);menu.getMenu().add(0,11,11,"Turmaler / egendefinerte turer");menu.getMenu().add(0,10,10,"Tilbakemelding / feilmelding");try{JSONObject draft=new JSONObject(getSharedPreferences("draft",0).getString("payload","{}"));DistributionRun run=DistributionState.read(draft.optJSONObject("distribution"));if(run!=null&&run.finishedMillis<0){if(run.events.size()<run.deadlines.length){int n=run.events.size()+1;menu.getMenu().add(0,7,0,"Stopp "+n+": Rygget til rampe");menu.getMenu().add(0,8,1,"Avbryt stopp "+n+" …");}else menu.getMenu().add(0,9,0,"Tilbake ved skolen: Avslutt tur");}}catch(Exception ignored){}menu.setOnMenuItemClickListener(item->{switch(item.getItemId()){case 0:continueForm();break;case 1:newTrip();break;case 2:history();break;case 3:manageLoad();break;case 4:settings();break;case 5:sync();break;case 6:updates.check(true);break;case 10:feedbackForm();break;case 11:paramTrips.open();break;case 7:case 8:case 9:menuDistribution(item.getItemId());break;}return true;});menu.show();}
 public void onBackPressed(){if(!authenticated){super.onBackPressed();return;}if(!page.equals("form")){continueForm();return;}persistDraft();super.onBackPressed();}
 void section(String title){TextView label=text(title,15,TEAL);label.setTypeface(null,Typeface.BOLD);label.setPadding(0,dp(20),0,dp(8));body.addView(label);}
 Runnable clockTick=new Runnable(){public void run(){restoreClock();refreshDistribution();refreshStops();if(page.equals("form")&&trip!=4&&inputs.containsKey("minutes")&&getSharedPreferences("trip_clock",0).getBoolean("completed",false)){inputs.get("minutes").setText(String.format(Locale.ROOT,"%.4f",tripClock.accumulated/60000.0));persistDraft();getSharedPreferences("trip_clock",0).edit().remove("completed").commit();}paintClock();paintDistributionClock();timer.postDelayed(this,500);}};
 void clockControls(){LinearLayout card=new LinearLayout(this);regularClock=card;card.setOrientation(1);card.setBackground(background(PANEL));card.setPadding(dp(14),dp(10),dp(14),dp(10));body.addView(card);card.addView(text("TIDTAKING",12,MUTED));clockView=text("00:00:00",32,TEAL);clockView.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);card.addView(clockView);LinearLayout row=new LinearLayout(this);card.addView(row);clockStart=button(row,"Start",()->startClock(),true);button(row,"Pause",()->{tripClock.stop(SystemClock.elapsedRealtime(),System.currentTimeMillis(),boot());persistClock();TimerService.show(this,"show");paintClock();},false);clockStop=button(row,"Stopp",()->stopClock(),false);button(card,"Nullstill klokke …",()->dialog().setTitle("Nullstill tidtaking?").setMessage("Den målte tiden slettes. Manuelt registrert tid beholdes.").setNegativeButton("Avbryt",null).setPositiveButton("Nullstill",(d,w)->{TimerService.dismiss(this);tripClock.reset();persistClock();paintClock();}).show(),false);card.addView(text("Start fyller inn dato og starttid. Stopp fyller inn forbrukt tid. Klokken fortsetter med skjermen av.",12,MUTED));}
 void startClock(){if(!requireLogin())return;if(tripClock.running)return;if(tripClock.accumulated==0){long now=System.currentTimeMillis();inputs.get("date").setText(new SimpleDateFormat("yyyy-MM-dd",Locale.ROOT).format(new Date(now)));inputs.get("start_time").setText(new SimpleDateFormat("HH:mm",Locale.ROOT).format(new Date(now)));}tripClock.start(SystemClock.elapsedRealtime(),System.currentTimeMillis(),boot());persistClock();persistDraft();notificationTimer();paintClock();}
 void stopClock(){TimerService.dismiss(this);tripClock.stop(SystemClock.elapsedRealtime(),System.currentTimeMillis(),boot());persistClock();if(clockMillis()>0&&page.equals("form")){inputs.get("minutes").setText(String.format(Locale.ROOT,"%.4f",clockMillis()/60000.0));persistDraft();}paintClock();}
 void paintClock(){if(clockView==null||!page.equals("form"))return;clockView.setText(TripTimer.format(clockMillis()));clockStart.setEnabled(!tripClock.running);clockStart.setText(tripClock.accumulated>0?"Fortsett":"Start");clockStop.setEnabled(tripClock.running||tripClock.accumulated>0);}
 int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(5),0,dp(6));return t;}
 GradientDrawable background(int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(12));return d;}
 Button button(LinearLayout box,String title,Runnable run,boolean accent){Button b=new Button(this);b.setText(title);b.setAllCaps(false);b.setTextSize(14);b.setTextColor(accent?BG:TEXT);b.setBackground(background(accent?TEAL:PANEL));b.setPadding(dp(10),dp(9),dp(10),dp(9));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(box.getOrientation()==LinearLayout.HORIZONTAL?0:-1,dp(48),box.getOrientation()==LinearLayout.HORIZONTAL?1:0);lp.setMargins(dp(3),dp(4),dp(3),dp(4));box.addView(b,lp);b.setOnClickListener(v->{if(authenticated||page.equals("settings")&&title.equals("Logg inn"))run.run();else requireLogin();});return b;}
 EditText field(String key,String label,String value,boolean number,boolean secret){body.addView(text(label,14,MUTED));EditText e=new EditText(this);e.setTextColor(TEXT);e.setTextSize(18);e.setSingleLine(!key.equals("notes"));e.setBackground(background(PANEL));e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setInputType(secret?InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD:number?InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL|InputType.TYPE_NUMBER_FLAG_SIGNED:InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);if(key.equals("notes")){e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);e.setMinLines(2);}e.setText(value);if(number||key.equals("minutes")){LinearLayout row=new LinearLayout(this);body.addView(row);row.addView(e,new LinearLayout.LayoutParams(0,-2,1));Button omit=new Button(this);omit.setText("-");omit.setContentDescription("Bevisst utelatt: "+label);omit.setOnClickListener(v->e.setText("-"));row.addView(omit,new LinearLayout.LayoutParams(dp(48),dp(48)));}else body.addView(e,new LinearLayout.LayoutParams(-1,-2));inputs.put(key,e);return e;}
 EditText dropdown(String key,String label,String value){
  body.addView(text(label+" ▾",14,MUTED));AutoCompleteTextView e=new AutoCompleteTextView(this);e.setTextColor(TEXT);e.setTextSize(18);e.setSingleLine(true);e.setBackground(background(PANEL));e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setThreshold(0);
  Set<String> names=new TreeSet<>(String.CASE_INSENSITIVE_ORDER);try{for(JSONObject r:db.rows(false))names.add(r.getJSONObject("payload").getString(key));JSONArray remote=new JSONArray(getSharedPreferences("cloud",0).getString("choices","[]"));for(int i=0;i<remote.length();i++)names.add(remote.getJSONObject(i).getString(key));}catch(Exception ignored){}
  e.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_dropdown_item_1line,new ArrayList<String>(names)));if(key.equals("course")){try{JSONArray courses=new JSONArray(getSharedPreferences("cloud",0).getString("course_setup","[]"));for(int i=0;i<courses.length();i++)names.add(courses.getJSONObject(i).getString("name"));e.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_dropdown_item_1line,new ArrayList<String>(names)));}catch(Exception ignored){}}e.setText(value);e.setOnClickListener(v->e.showDropDown());body.addView(e,new LinearLayout.LayoutParams(-1,-2));inputs.put(key,e);e.setCompoundDrawablesWithIntrinsicBounds(0,0,android.R.drawable.arrow_down_float,0);e.setOnTouchListener((v,event)->{if(event.getAction()==android.view.MotionEvent.ACTION_UP&&event.getX()>e.getWidth()-dp(56)){e.showDropDown();return true;}return false;});return e;
 }
 double duration(String raw)throws Exception{String[] parts=raw.replace(',','.').split(":");if(parts.length==1)return Double.parseDouble(parts[0]);if(parts.length>3)throw new Exception("Tid: minutter, mm:ss eller tt:mm:ss.");double seconds=0;for(int i=0;i<parts.length;i++){double v=Double.parseDouble(parts[i]);if(v<0||i>0&&v>=60)throw new Exception("Ugyldig forbrukt tid.");seconds=seconds*60+v;}return seconds/60;}
 void form(JSONObject saved){if(!requireLogin())return;String previous="",next=saved==null?"":saved.optString("id");try{String raw=getSharedPreferences("draft",0).getString("payload","");if(!raw.isEmpty())previous=new JSONObject(raw).optString("id");}catch(Exception ignored){}if(!previous.equals(next)){try{JSONObject current=new JSONObject(getSharedPreferences("draft",0).getString("payload","{}"));JSONObject log=current.optJSONObject("distribution");if(log!=null&&log.isNull("finished_minutes")){alert("Avslutt distribusjonsoppdraget først. Velg Fortsett tur i menyen.");return;}}catch(Exception ignored){}if(tripClock.running){alert("Stopp tidtakingen på turen som pågår først. Velg Fortsett tur i menyen.");return;}TimerService.dismiss(this);tripClock.reset();persistClock();}DistributionRun previousRun=distributionRun;try{restoreDistribution(saved==null?null:saved.optJSONObject("distribution"));}catch(Exception e){distributionRun=previousRun;alert("Kan ikke åpne stopploggen: "+e.getMessage());return;}seenDistributionVersion=getSharedPreferences("draft",0).getLong("distribution_version",0);page="form";clockView=null;distributionHost=null;distributionLive=null;body.removeAllViews();inputs.clear();ratings.clear();managedEdit=saved==null?null:saved.optJSONObject("_managed");editId=saved==null?null:saved.optString("id",null);trip=saved==null?1:saved.optInt("trip",1);android.content.SharedPreferences prefs=getSharedPreferences("form",0);
  body.addView(text(editId==null?"Ny kjøretur":"Rediger kjøretur",22,TEXT));clockControls();section("1 · Sjåfør og kjøretøy");body.addView(text(managedEdit==null?"Fyll inn når du har stanset. Turen lagres på telefonen før den sendes.":"Redigerer skyversjonen. Krever nett ved lagring.",13,MUTED));
  dropdown("driver","Sjåfør",saved==null?"":saved.optString("driver"));dropdown("course","Kurs",saved==null?prefs.getString("course",""):saved.optString("course"));dropdown("vehicle","Bil",saved==null?prefs.getString("vehicle",""):saved.optString("vehicle"));
  body.addView(text("Tur",14,MUTED));tripChoices=new LinearLayout(this);tripChoices.setOrientation(1);body.addView(tripChoices);paintTrips();inputs.get("course").addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){paintTrips();}public void afterTextChanged(android.text.Editable e){}});
  distributionHost=new LinearLayout(this);distributionHost.setOrientation(1);body.addView(distributionHost);
  section("2 · Tid og målinger");body.addView(text("Du kan lagre med tomme felt. Skriv - for bevisst utelatt. Tom gjennomsnittsfart beregnes automatisk; notater er valgfrie.",13,MUTED));
  field("date","Dato (ÅÅÅÅ-MM-DD)",saved==null?new SimpleDateFormat("yyyy-MM-dd",Locale.ROOT).format(new Date()):saved.optString("date"),false,false);field("start_time","Starttid (TT:MM)",saved==null?"":saved.optString("start_time"),false,false);
  field("minutes","Forbrukt tid (minutter eller mm:ss)",saved==null?"":saved.optString("minutes"),false,false);field("km","Kjørt (km)",saved==null?"":saved.optString("km"),true,false);field("liters","Drivstoff brukt totalt (liter)",saved==null?"":saved.optString("liters"),true,false);field("stops","Unødige stopp (kan skrives manuelt)",saved==null?"0":saved.optString("stops"),true,false);seenStopsVersion=getSharedPreferences("draft",0).getLong("stops_version",0);inputs.get("stops").addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){}public void afterTextChanged(android.text.Editable e){manualStops();}});Button add=button(body,"+ Unødig stans",()->addStop(),false);add.setBackground(background(Color.rgb(194,44,58)));add.setTextColor(Color.WHITE);
  field("average_speed","Gjennomsnitt km/t (tomt = beregnet)",saved==null?"":saved.optString("average_speed"),true,false);
  TextView consumption=text("Forbruk per 10 km: fyll inn liter og km",18,TEAL);body.addView(consumption);android.text.TextWatcher watch=new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int count){try{double km=Double.parseDouble(inputs.get("km").getText().toString().replace(',','.'));double liter=Double.parseDouble(inputs.get("liters").getText().toString().replace(',','.'));consumption.setText(km>0?String.format(Locale.getDefault(),"Forbruk per 10 km: %.2f liter",10*liter/km):"Legg inn distanse større enn null");}catch(Exception ignored){consumption.setText("Forbruk per 10 km: fyll inn liter og km");}}public void afterTextChanged(android.text.Editable e){}};inputs.get("km").addTextChangedListener(watch);inputs.get("liters").addTextChangedListener(watch);watch.onTextChanged("",0,0,0);
  section("3 · Vurdering");
  for(String k:QUAL){body.addView(text(k.equals("avpassing")?"Fartsavpassing":k.equals("økning")?"Fartsøkning":k.substring(0,1).toUpperCase()+k.substring(1),14,MUTED));ratings.put(k,saved==null?"":saved.optString(k,""));LinearLayout choices=new LinearLayout(this);body.addView(choices);Map<String,Button> buttons=new HashMap<>();for(String value:new String[]{"Bra","Middel","Svak","-"}){Button b=button(choices,value.equals("Middel")?"Middels":value,()->{ratings.put(k,value);for(Map.Entry<String,Button> item:buttons.entrySet()){item.getValue().setBackground(background(item.getKey().equals(value)?TEAL:PANEL));item.getValue().setTextColor(item.getKey().equals(value)?BG:TEXT);}},ratings.get(k).equals(value));buttons.put(value,b);}}
  section("4 · Signatur og notater");field("teacher","Lærer / signatur (navn eller initialer)",saved==null?prefs.getString("teacher",""):saved.optString("teacher"),false,false);
  field("notes","Notater",saved==null?"":saved.optString("notes"),false,false);button(body,managedEdit==null?"Lagre tur på telefonen":"Lagre endringer i skyen",()->save(),true);paintClock();paintDistribution();if(distributionRun!=null&&distributionRun.finishedMillis<0)notificationTimer();scroll.post(()->scroll.smoothScrollTo(0,0));
 }
 void save(){if(!requireLogin())return;refreshStops();if(tripClock.running){alert("Stopp tidtakingen før du lagrer turen.");return;}try{JSONObject plan=courseDistribution(inputs.get("course").getText().toString());if(editId==null&&trip==4&&plan!=null&&plan.optInt("stop_count")>0&&distributionRun==null)throw new Exception("Trykk Start distribusjonsoppdrag og registrer leveringsstoppene først.");if(distributionRun!=null&&distributionRun.finishedMillis<0)throw new Exception("Merk alle stopp og avslutt distribusjonsoppdraget først. Utkastet er lagret på telefonen.");JSONObject p=new JSONObject();if(distributionRun!=null)p.put("distribution",distributionJson(false));p.put("id",editId==null?UUID.randomUUID().toString():editId);for(String k:new String[]{"driver","course","vehicle"}){String v=inputs.get(k).getText().toString().trim();if(v.length()>100)throw new Exception("Fyll inn sjåfør, kurs og kjøretøy (maks 100 tegn).");p.put(k,v);}if(editId==null&&trip>activeTrips(p.optString("course")))throw new Exception("Denne turen er ikke aktivert på kurset. Velg en aktiv tur.");p.put("trip",trip);if(distributionRun!=null)inputs.get("minutes").setText(String.format(Locale.ROOT,"%.4f",distributionRun.finishedMillis/60000.0));for(String k:new String[]{"minutes","km","liters","stops"}){String raw=inputs.get(k).getText().toString().trim();if(raw.isEmpty()||raw.equals("-")){p.put(k,raw);continue;}double v=k.equals("minutes")?duration(raw):Double.parseDouble(raw.replace(',','.'));if(!Double.isFinite(v)||v<0||(k.equals("minutes")||k.equals("km"))&&v==0||k.equals("stops")&&v!=Math.floor(v))throw new Exception("Kontroller tid, km, liter og hele antall stopp.");p.put(k,v);}for(String k:QUAL)p.put(k,ratings.get(k));for(String k:new String[]{"date","start_time","teacher"})p.put(k,inputs.get(k).getText().toString().trim());
  if(p.getString("teacher").length()>100)throw new Exception("Lærer/signatur: maks 100 tegn.");
  for(String k:new String[]{"date","start_time"}){String value=p.getString(k);if(!value.isEmpty()&&!value.equals("-")){String pattern=k.equals("date")?"yyyy-MM-dd":"HH:mm";SimpleDateFormat format=new SimpleDateFormat(pattern,Locale.ROOT);format.setLenient(false);java.text.ParsePosition position=new java.text.ParsePosition(0);if(format.parse(value,position)==null||position.getIndex()!=value.length()||!value.matches(k.equals("date")?"[0-9]{4}-[0-9]{2}-[0-9]{2}":"[0-9]{2}:[0-9]{2}"))throw new Exception("Kontroller dato og starttid.");}}
  String speed=inputs.get("average_speed").getText().toString().trim();if(speed.equals("-"))p.put("average_speed","-");else if(!speed.isEmpty()){double value=Double.parseDouble(speed.replace(',','.'));if(!Double.isFinite(value)||value<0)throw new Exception("Kontroller gjennomsnittsfart.");p.put("average_speed",value);}String notes=inputs.get("notes").getText().toString();if(notes.length()>2000)throw new Exception("…21278 tokens truncated…coalesce(current_revision,0)+1;
 insert into public.ysk_trip_template_versions values(p_org,p_id,next_revision,p_definition);
 insert into public.ysk_trip_templates values(p_org,p_id,next_revision,p_definition->>'name',p_definition) on conflict(organization_id,id) do update set revision=excluded.revision,name=excluded.name,definition=excluded.definition;
 return jsonb_build_object('id',p_id,'revision',next_revision,'definition',p_definition);
end;$$;
revoke all on function public.ysk_save_template(uuid,uuid,integer,jsonb) from public,anon,authenticated;
grant execute on function public.ysk_save_template(uuid,uuid,integer,jsonb) to service_role;
create or replace function public.ysk_save_template_run(p_user uuid,p_body jsonb) returns jsonb language plpgsql security invoker set search_path='' as $$
declare m public.ysk_memberships;old public.ysk_template_runs;result public.ysk_template_runs;run_id uuid;expected integer;
begin
 select * into m from public.ysk_memberships where user_id=p_user and active;
 if m.user_id is null then return jsonb_build_object('status',403,'message','Ingen aktiv skoletilgang.');end if;
 run_id:=(p_body->>'id')::uuid;expected:=(p_body->>'expected_revision')::integer;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(run_id::text,0));
 select * into old from public.ysk_template_runs where id=run_id;
 if old.id is not null then
  if old.organization_id<>m.organization_id or (old.owner_id<>p_user and m.role<>'admin') then return jsonb_build_object('status',403,'message','Turen tilhører en annen bruker.');end if;
  if old.revision<>expected then
   if old.payload=p_body->'payload' then return to_jsonb(old);end if;
   return jsonb_build_object('status',409,'message','Turen er endret. Hent siste versjon.');
  end if;
  if old.template_id<>(p_body->>'template_id')::uuid or old.template_revision<>(p_body->>'template_revision')::integer then return jsonb_build_object('status',400,'message','Gamle turer beholder turmalen.');end if;
  update public.ysk_template_runs set payload=p_body->'payload',revision=revision+1,updated_at=now() where id=run_id returning * into result;
 else
  if expected<>0 then return jsonb_build_object('status',409,'message','Turen finnes ikke.');end if;
  insert into public.ysk_template_runs(id,organization_id,owner_id,template_id,template_revision,snapshot,payload) values(run_id,m.organization_id,p_user,(p_body->>'template_id')::uuid,(p_body->>'template_revision')::integer,p_body->'snapshot',p_body->'payload') returning * into result;
 end if;
 return to_jsonb(result);
end;$$;
revoke all on function public.ysk_save_template_run(uuid,jsonb) from public,anon,authenticated;
grant execute on function public.ysk_save_template_run(uuid,jsonb) to service_role;
