package no.talappen.ysk;
import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import android.text.InputType;import org.json.*;import java.util.*;import java.text.SimpleDateFormat;
public class MainActivity extends Activity {
 final int BG=Color.rgb(11,20,35),PANEL=Color.rgb(20,34,56),TEAL=Color.rgb(73,216,189),TEXT=Color.rgb(237,244,255),MUTED=Color.rgb(153,171,195);
 final String[] QUAL={"trafikksikkerhet","avpassing","økning","komfort"};LinearLayout body;TextView status;Map<String,EditText> inputs=new HashMap<>();Map<String,String> ratings=new HashMap<>();int trip=1;String editId=null;boolean syncing=false,adminBusy=false;TripDb db;Handler timer=new Handler(Looper.getMainLooper());String page="";Updates updates;Button updateButton;
 Runnable tick=new Runnable(){public void run(){updateStatus();updates.automatic();timer.postDelayed(this,5000);}};
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);db=new TripDb(this);updates=new Updates(this);
  LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(BG);root.setPadding(dp(18),dp(12),dp(18),dp(12));setContentView(root);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(dp(18),dp(12)+insets.getSystemWindowInsetTop(),dp(18),dp(12)+insets.getSystemWindowInsetBottom());return insets;});
  TextView badge=text("YSK / KJØRESTUDIO",13,TEAL);root.addView(badge);TextView title=text("Turer ute på veien",25,TEXT);title.setTypeface(null,Typeface.BOLD);root.addView(title);status=text("Lagrer på telefonen · også uten nett",13,MUTED);root.addView(status);
  LinearLayout nav=new LinearLayout(this);root.addView(nav);button(nav,"Ny tur",()->form(null),false);button(nav,"Mine turer",()->history(),false);button(nav,"Innstillinger",()->settings(),false);
  ScrollView scroll=new ScrollView(this);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));body=new LinearLayout(this);body.setOrientation(1);scroll.addView(body);button(root,"Synkroniser nå",()->sync(),true);updateButton=button(root,"Sjekk oppdateringer",()->updates.check(true),false);if(b!=null&&b.containsKey("draft")){try{form(new JSONObject(b.getString("draft")));}catch(Exception ignored){form(null);}}else form(null);SyncJob.schedule(this);
 }
 public void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);if(page.equals("form")){try{JSONObject draft=new JSONObject();for(Map.Entry<String,EditText> e:inputs.entrySet())draft.put(e.getKey(),e.getValue().getText().toString());for(String k:QUAL)draft.put(k,ratings.get(k));draft.put("trip",trip);if(editId!=null)draft.put("id",editId);out.putString("draft",draft.toString());}catch(Exception ignored){}}}
 public void onResume(){super.onResume();timer.post(tick);updateStatus();updates.automatic();}
 public void onPause(){super.onPause();timer.removeCallbacks(tick);}
 public void onDestroy(){timer.removeCallbacks(tick);db.close();super.onDestroy();}
 int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(5),0,dp(6));return t;}
 GradientDrawable background(int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(12));return d;}
 Button button(LinearLayout box,String title,Runnable run,boolean accent){Button b=new Button(this);b.setText(title);b.setAllCaps(false);b.setTextSize(14);b.setTextColor(accent?BG:TEXT);b.setBackground(background(accent?TEAL:PANEL));b.setPadding(dp(10),dp(9),dp(10),dp(9));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(box.getOrientation()==LinearLayout.HORIZONTAL?0:-1,dp(52),box.getOrientation()==LinearLayout.HORIZONTAL?1:0);lp.setMargins(dp(3),dp(6),dp(3),dp(6));box.addView(b,lp);b.setOnClickListener(v->run.run());return b;}
 EditText field(String key,String label,String value,boolean number,boolean secret){body.addView(text(label,14,MUTED));EditText e=new EditText(this);e.setTextColor(TEXT);e.setTextSize(18);e.setSingleLine(!key.equals("notes"));e.setBackground(background(PANEL));e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setInputType(secret?InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD:number?InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL:InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);if(key.equals("notes")){e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);e.setMinLines(2);}e.setText(value);body.addView(e,new LinearLayout.LayoutParams(-1,-2));inputs.put(key,e);return e;}
 EditText dropdown(String key,String label,String value){
  body.addView(text(label+" ▾",14,MUTED));AutoCompleteTextView e=new AutoCompleteTextView(this);e.setTextColor(TEXT);e.setTextSize(18);e.setSingleLine(true);e.setBackground(background(PANEL));e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setThreshold(0);
  Set<String> names=new TreeSet<>(String.CASE_INSENSITIVE_ORDER);try{for(JSONObject r:db.rows(false))names.add(r.getJSONObject("payload").getString(key));JSONArray remote=new JSONArray(getSharedPreferences("cloud",0).getString("choices","[]"));for(int i=0;i<remote.length();i++)names.add(remote.getJSONObject(i).getString(key));}catch(Exception ignored){}
  e.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_dropdown_item_1line,new ArrayList<String>(names)));e.setText(value);e.setOnClickListener(v->e.showDropDown());body.addView(e,new LinearLayout.LayoutParams(-1,-2));inputs.put(key,e);button(body,"Velg lagret "+label.toLowerCase(),()->e.showDropDown(),false);return e;
 }
 double duration(String raw)throws Exception{String[] parts=raw.replace(',','.').split(":");if(parts.length==1)return Double.parseDouble(parts[0]);if(parts.length>3)throw new Exception("Tid: minutter, mm:ss eller tt:mm:ss.");double seconds=0;for(int i=0;i<parts.length;i++){double v=Double.parseDouble(parts[i]);if(v<0||i>0&&v>=60)throw new Exception("Ugyldig forbrukt tid.");seconds=seconds*60+v;}return seconds/60;}
 void form(JSONObject saved){page="form";body.removeAllViews();inputs.clear();ratings.clear();editId=saved==null?null:saved.optString("id",null);trip=saved==null?1:saved.optInt("trip",1);android.content.SharedPreferences prefs=getSharedPreferences("form",0);
  body.addView(text(saved==null?"Registrer kjøretur":"Rediger kjøretur",22,TEXT));body.addView(text("Fyll inn når du har stanset. Turen lagres på telefonen før den sendes.",13,MUTED));
  dropdown("driver","Sjåfør",saved==null?"":saved.optString("driver"));dropdown("course","Kurs",saved==null?prefs.getString("course",""):saved.optString("course"));dropdown("vehicle","Bil",saved==null?prefs.getString("vehicle",""):saved.optString("vehicle"));
  body.addView(text("Tur",14,MUTED));LinearLayout turns=new LinearLayout(this);body.addView(turns);List<Button> ts=new ArrayList<>();for(int n=1;n<=5;n++){final int selected=n;Button b=button(turns,String.valueOf(n),()->{trip=selected;for(int i=0;i<ts.size();i++){ts.get(i).setBackground(background(i+1==trip?TEAL:PANEL));ts.get(i).setTextColor(i+1==trip?BG:TEXT);}},n==trip);ts.add(b);}
  field("date","Dato (ÅÅÅÅ-MM-DD)",saved==null?new SimpleDateFormat("yyyy-MM-dd",Locale.ROOT).format(new Date()):saved.optString("date"),false,false);field("start_time","Starttid (TT:MM)",saved==null?"":saved.optString("start_time"),false,false);
  field("minutes","Forbrukt tid (minutter eller mm:ss)",saved==null?"":saved.optString("minutes"),false,false);field("km","Kjørt (km)",saved==null?"":saved.optString("km"),true,false);field("liters","Drivstoff brukt totalt (liter)",saved==null?"":saved.optString("liters"),true,false);field("stops","Unødige stopp",saved==null?"0":saved.optString("stops"),true,false);
  field("average_speed","Gjennomsnitt km/t (tomt = beregnet)",saved==null?"":saved.optString("average_speed"),true,false);
  TextView consumption=text("Forbruk per 10 km: fyll inn liter og km",18,TEAL);body.addView(consumption);android.text.TextWatcher watch=new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int count){try{double km=Double.parseDouble(inputs.get("km").getText().toString().replace(',','.'));double liter=Double.parseDouble(inputs.get("liters").getText().toString().replace(',','.'));consumption.setText(km>0?String.format(Locale.getDefault(),"Forbruk per 10 km: %.2f liter",10*liter/km):"Legg inn distanse større enn null");}catch(Exception ignored){consumption.setText("Forbruk per 10 km: fyll inn liter og km");}}public void afterTextChanged(android.text.Editable e){}};inputs.get("km").addTextChangedListener(watch);inputs.get("liters").addTextChangedListener(watch);watch.onTextChanged("",0,0,0);
  body.addView(text("Kjørepoeng beregnes i PC-programmets rangering.",13,MUTED));
  for(String k:QUAL){body.addView(text(k.equals("avpassing")?"Fartsavpassing":k.equals("økning")?"Fartsøkning":k.substring(0,1).toUpperCase()+k.substring(1),14,MUTED));ratings.put(k,saved==null?"Middel":saved.optString(k,"Middel"));LinearLayout choices=new LinearLayout(this);body.addView(choices);Map<String,Button> buttons=new HashMap<>();for(String value:new String[]{"Bra","Middel","Svak"}){Button b=button(choices,value.equals("Middel")?"Middels":value,()->{ratings.put(k,value);for(Map.Entry<String,Button> item:buttons.entrySet()){item.getValue().setBackground(background(item.getKey().equals(value)?TEAL:PANEL));item.getValue().setTextColor(item.getKey().equals(value)?BG:TEXT);}},ratings.get(k).equals(value));buttons.put(value,b);}}
  field("teacher","Lærer / signatur (navn eller initialer)",saved==null?prefs.getString("teacher",""):saved.optString("teacher"),false,false);
  field("notes","Notater",saved==null?"":saved.optString("notes"),false,false);button(body,"Lagre tur på telefonen",()->save(),true);
 }
 void save(){try{JSONObject p=new JSONObject();p.put("id",editId==null?UUID.randomUUID().toString():editId);for(String k:new String[]{"driver","course","vehicle"}){String v=inputs.get(k).getText().toString().trim();if(v.isEmpty()||v.length()>100)throw new Exception("Fyll inn sjåfør, kurs og kjøretøy (maks 100 tegn).");p.put(k,v);}p.put("trip",trip);for(String k:new String[]{"minutes","km","liters","stops"}){double v=k.equals("minutes")?duration(inputs.get(k).getText().toString()):Double.parseDouble(inputs.get(k).getText().toString().replace(',','.'));if(Double.isNaN(v)||Double.isInfinite(v)||v<0||(k.equals("minutes")||k.equals("km"))&&v==0||k.equals("stops")&&v!=Math.floor(v))throw new Exception("Kontroller tid, km, liter og hele antall stopp.");p.put(k,v);}for(String k:QUAL)p.put(k,ratings.get(k));for(String k:new String[]{"date","start_time","teacher"})p.put(k,inputs.get(k).getText().toString().trim());
  if(p.getString("teacher").length()>100)throw new Exception("Lærer/signatur: maks 100 tegn.");
  for(String k:new String[]{"date","start_time"}){String value=p.getString(k);if(!value.isEmpty()){String pattern=k.equals("date")?"yyyy-MM-dd":"HH:mm";SimpleDateFormat format=new SimpleDateFormat(pattern,Locale.ROOT);format.setLenient(false);java.text.ParsePosition position=new java.text.ParsePosition(0);if(format.parse(value,position)==null||position.getIndex()!=value.length()||!value.matches(k.equals("date")?"[0-9]{4}-[0-9]{2}-[0-9]{2}":"[0-9]{2}:[0-9]{2}"))throw new Exception("Kontroller dato og starttid.");}}
  String speed=inputs.get("average_speed").getText().toString().trim();if(!speed.isEmpty()){double value=Double.parseDouble(speed.replace(',','.'));if(!Double.isFinite(value)||value<0)throw new Exception("Kontroller gjennomsnittsfart.");p.put("average_speed",value);}String notes=inputs.get("notes").getText().toString();if(notes.length()>2000)throw new Exception("Notater: maks 2000 tegn.");p.put("notes",notes);p.put("updated",new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss",Locale.ROOT).format(new Date()));db.save(p);getSharedPreferences("form",0).edit().putString("course",p.getString("course")).putString("vehicle",p.getString("vehicle")).putString("teacher",p.getString("teacher")).apply();Toast.makeText(this,"Lagret på telefonen",Toast.LENGTH_LONG).show();SyncJob.schedule(this);history();sync();}catch(Exception e){alert(e.getMessage());}}
 void history(){page="history";body.removeAllViews();body.addView(text("Mine turer",23,TEXT));body.addView(text("Trykk på en tur for å redigere. «Sendt» betyr lagret i skyen; PC-en henter når den er på.",13,MUTED));try{List<JSONObject> rows=db.rows(false);if(rows.isEmpty())body.addView(text("Ingen turer ennå. Velg Ny tur.",18,TEXT));for(JSONObject r:rows){JSONObject p=r.getJSONObject("payload");LinearLayout card=new LinearLayout(this);card.setOrientation(1);card.setBackground(background(PANEL));card.setPadding(dp(15),dp(10),dp(15),dp(10));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(8),0,dp(8));body.addView(card,lp);card.addView(text(p.getString("driver")+" · Tur "+p.getInt("trip"),20,TEXT));card.addView(text(p.getString("course")+" · "+p.getString("vehicle"),13,MUTED));double km=p.getDouble("km");card.addView(text(String.format(Locale.getDefault(),"%.2f L/10 km  ·  %.1f km/t",10*p.getDouble("liters")/km,p.optDouble("average_speed",60*km/p.getDouble("minutes"))),16,TEAL));card.addView(text(p.optString("date")+"  "+p.optString("start_time")+" · Lærer: "+p.optString("teacher"),13,MUTED));boolean sent=r.getString("state").equals("sent");card.addView(text(sent?"SENDT TIL SKY":"VENTER PÅ SENDING",13,sent?TEAL:Color.rgb(255,199,117)));if(!r.optString("error").isEmpty())card.addView(text(r.optString("error"),13,Color.rgb(255,138,149)));card.setOnClickListener(v->form(p));}}catch(Exception e){alert(e.getMessage());}updateStatus();}
 void settings(){page="settings";body.removeAllViews();inputs.clear();body.addView(text("Koble telefon og PC",23,TEXT));body.addView(text("Bruk skolens Supabase-prosjekt og din egen lærerkonto. Etter skoleaktivering samles lærernes turer på PC. Uten tilkobling fungerer lokal lagring fortsatt.",14,MUTED));android.content.SharedPreferences p=getSharedPreferences("cloud",0);field("url","Supabase Project URL",p.getString("url","https://otuemdgmymgognzghmnu.supabase.co"),false,false).setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);field("api","Publishable / anon key",p.getString("api","sb_publishable_9-BPAUPJ5gv_MJ1hz6ah0g_yoz3npSu"),false,false).setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD);field("email","E-post",p.getString("email",""),false,false).setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);field("password","Passord","",false,true);
  button(body,"Admin / lærere",()->admin(),false);
  button(body,"Logg inn og koble til",()->{String url=inputs.get("url").getText().toString(),api=inputs.get("api").getText().toString(),email=inputs.get("email").getText().toString(),pass=inputs.get("password").getText().toString();inputs.get("password").setText("");status.setText("Kobler til …");new Thread(()->{try{Sync.login(this,url,api,email,pass);runOnUiThread(()->{if(isDestroyed())return;Toast.makeText(this,"Tilkoblet",Toast.LENGTH_LONG).show();SyncJob.schedule(this);history();sync();});}catch(Exception e){runOnUiThread(()->{if(!isDestroyed())alert(e.getMessage());});}},"YSK-login").start();},true);body.addView(text("Passordet lagres ikke. Innloggingsøkten krypteres med Android Keystore. Oppsettsveiledning og databasefil følger PC-pakken.",13,MUTED));
 }
 void admin(){page="admin";body.removeAllViews();inputs.clear();body.addView(text("Admin / lærere",23,TEXT));body.addView(text("Skole/admin krever aktivering i Supabase. Hver lærer skal ha egen konto.",14,MUTED));button(body,"Hent lærere",()->adminLoad(),true);adminLoad();}
 void adminLoad(){if(adminBusy)return;adminBusy=true;status.setText("Henter adminrettigheter …");new Thread(()->{try{JSONObject me=Sync.admin(this,new JSONObject().put("action","me")).getJSONObject("member");if(!me.getString("role").equals("admin"))throw new Exception("Du er lærer. Bare administrator kan opprette brukere.");JSONObject list=Sync.admin(this,new JSONObject().put("action","list"));runOnUiThread(()->{adminBusy=false;if(!isDestroyed()&&page.equals("admin"))adminRender(me,list);});}catch(Exception e){runOnUiThread(()->{adminBusy=false;if(!isDestroyed()&&page.equals("admin"))alert(e.getMessage());});}},"YSK-admin").start();}
 void adminRender(JSONObject me,JSONObject list){body.removeAllViews();inputs.clear();body.addView(text("Lærere i skolen",23,TEXT));body.addView(text("Admin: "+me.optString("display_name"),14,TEAL));field("admin_name","Ny lærers navn","",false,false);field("admin_email","E-post","",false,false).setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);field("admin_password","Startpassord (minst 12 tegn)","",false,true);
  body.addView(text("Rolle",14,MUTED));Spinner roles=new Spinner(this);roles.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Lærer","Administrator"}));roles.setBackground(background(TEAL));body.addView(roles);body.addView(text("Du gir læreren e-post og startpassord selv. Programmet sender ingen e-post.",13,MUTED));
  button(body,"Opprett bruker",()->{try{JSONObject b=new JSONObject().put("action","create").put("name",inputs.get("admin_name").getText().toString()).put("email",inputs.get("admin_email").getText().toString()).put("password",inputs.get("admin_password").getText().toString()).put("role",roles.getSelectedItemPosition()==0?"teacher":"admin");inputs.get("admin_password").setText("");adminAction(b);}catch(Exception e){alert(e.getMessage());}},true);
  JSONArray members=list.optJSONArray("members");if(members!=null)for(int i=0;i<members.length();i++){JSONObject member=members.optJSONObject(i);if(member==null)continue;body.addView(text(member.optString("display_name")+" · "+(member.optBoolean("active")?"Aktiv":"Deaktivert"),18,TEXT));body.addView(text(member.optString("email")+" · "+member.optString("role"),13,MUTED));Spinner channel=new Spinner(this);ArrayAdapter<String> channels=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"stable","dev"});channel.setAdapter(channels);channel.setSelection(member.optString("update_channel","stable").equals("dev")?1:0);body.addView(channel);button(body,"Lagre oppdateringskanal",()->{try{adminAction(new JSONObject().put("action","set_channel").put("user_id",member.getString("user_id")).put("channel",channel.getSelectedItem().toString()));}catch(Exception e){alert(e.getMessage());}},false);if(member.optString("role").equals("teacher"))button(body,member.optBoolean("active")?"Deaktiver lærer":"Aktiver lærer",()->{try{adminAction(new JSONObject().put("action","set_active").put("user_id",member.getString("user_id")).put("active",!member.getBoolean("active")));}catch(Exception e){alert(e.getMessage());}},false);}
  button(body,"Oppdater liste",()->adminLoad(),false);status.setText("Administrator · "+(members==null?0:members.length())+" brukere");
 }
 void adminAction(JSONObject bodyJson){if(adminBusy)return;adminBusy=true;status.setText("Utfører adminhandling …");new Thread(()->{try{JSONObject result=Sync.admin(this,bodyJson);runOnUiThread(()->{adminBusy=false;if(!isDestroyed()&&page.equals("admin")){Toast.makeText(this,result.optString("message","Utført"),Toast.LENGTH_LONG).show();adminLoad();}});}catch(Exception e){runOnUiThread(()->{adminBusy=false;if(!isDestroyed())alert(e.getMessage());});}},"YSK-admin-write").start();}
 void sync(){if(syncing)return;syncing=true;status.setText("Sender ventende turer …");new Thread(()->{String message;try{message=Sync.run(this);}catch(Exception e){message="Lagret lokalt. Venter: "+e.getMessage();}final String result=message;getSharedPreferences("cloud",0).edit().putString("last_status",message).apply();runOnUiThread(()->{if(isDestroyed())return;syncing=false;status.setText(result);if(page.equals("history"))history();});},"YSK-manual-sync").start();}
 void updateStatus(){if(syncing)return;try{int pending=db.rows(true).size();status.setText(pending>0?pending+" turer venter · lagret på telefonen":getSharedPreferences("cloud",0).getString("last_status","Klar · også uten nett"));}catch(Exception ignored){}}
 void alert(String message){new AlertDialog.Builder(this).setTitle("YSK Kjørestudio").setMessage(message==null?"Ukjent feil":message).setPositiveButton("OK",null).show();}
}
