package no.talappen.ysk;
import android.app.*;import android.content.*;import android.os.*;import android.text.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;
/** School parameter bank and versioned dynamic trip forms. */
public final class ParamTrips {
 final MainActivity a;JSONObject catalog;boolean busy=false;String scope="";JSONObject current,run;Map<String,EditText> edits=new HashMap<>();Map<String,Spinner> choices=new HashMap<>();Map<String,Long> clocks=new HashMap<>();AlertDialog formDialog;boolean rendering=false;
 ParamTrips(MainActivity activity){a=activity;}
 android.content.SharedPreferences prefs(){return a.getSharedPreferences("parameter_trips_"+scope,0);}
 String accountScope(){try{JSONObject m=new JSONObject(a.getSharedPreferences("cloud",0).getString("account","{}")).getJSONObject("member");return m.getString("organization_id")+"_"+m.getString("user_id");}catch(Exception e){return "";}}
 interface Done{void result(JSONObject r)throws Exception;}
 void request(JSONObject body,Done done){if(busy||!a.requireLogin())return;busy=true;final String expectedScope=scope;new Thread(()->{try{JSONObject r=Sync.admin(a,body);a.runOnUiThread(()->{busy=false;if(a.isDestroyed()||!a.authenticated||!expectedScope.equals(accountScope()))return;try{done.result(r);}catch(Exception e){a.alert(e.getMessage());}});}catch(Exception e){a.runOnUiThread(()->{busy=false;if(!a.isDestroyed()&&a.authenticated)a.alert("Lokalt utkast beholdes. "+e.getMessage());});}},"YSK-templates").start();}
 JSONObject action(String name){try{return new JSONObject().put("action",name);}catch(Exception e){throw new RuntimeException(e);}}
 void open(){if(!a.requireLogin())return;try{JSONObject me=new JSONObject(a.getSharedPreferences("cloud",0).getString("account","{}")).getJSONObject("member");String nextScope=me.getString("organization_id")+"_"+me.getString("user_id");if(!nextScope.equals(scope)){catalog=null;current=null;run=null;edits.clear();choices.clear();}scope=nextScope;String cached=prefs().getString("catalog","");if(!cached.isEmpty())catalog=new JSONObject(cached);}catch(Exception e){a.alert("Logg inn på nytt først.");return;}request(action("template_catalog"),r->{catalog=r;prefs().edit().putString("catalog",r.toString()).commit();menu();});if(catalog!=null)menu();}
 void menu(){if(catalog==null)return;ArrayList<String> labels=new ArrayList<>(Arrays.asList("Ny tur fra turmal","Fortsett lokalt utkast","Registrerte parameterturer","Send ventende tur","Oppdater turmaler"));if(catalog.optString("role").equals("admin"))labels.addAll(Arrays.asList("Parameterbank","Endre turmal","Ny egendefinert turmal","Turmaler i kurs"));a.dialog().setTitle("Turmaler / egendefinerte turer").setItems(labels.toArray(new String[0]),(d,n)->{switch(n){case 0:pick(false);break;case 1:resume();break;case 2:history(0,new JSONArray());break;case 3:sendPending();break;case 4:open();break;case 5:bank();break;case 6:pick(true);break;case 7:editor(null);break;case 8:course();break;}}).show();}
 void pick(boolean edit){if(edit){pickForCourse(true,"");return;}LinearLayout p=panel();EditText courseName=field(p,"Kursnavn","",false);a.dialog().setTitle("Kurs for turen").setView(p).setNegativeButton("Avbryt",null).setPositiveButton("Velg turmal",(d,n)->pickForCourse(false,courseName.getText().toString().trim())).show();}
 void pickForCourse(boolean edit,String courseName){try{JSONArray ts=catalog.getJSONArray("templates");if(!edit){if(courseName.isEmpty()){a.alert("Angi kursnavn.");return;}JSONArray courses=catalog.getJSONArray("courses"),ids=null;for(int i=0;i<courses.length();i++)if(courses.getJSONObject(i).getString("name").equals(courseName))ids=courses.getJSONObject(i).getJSONArray("template_ids");if(ids!=null){JSONArray filtered=new JSONArray();for(int i=0;i<ts.length();i++)for(int j=0;j<ids.length();j++)if(ts.getJSONObject(i).getString("id").equals(ids.getString(j)))filtered.put(ts.getJSONObject(i));ts=filtered;}if(ts.length()==0){a.alert("Ingen turmaler er aktivert i kurset.");return;}}final JSONArray selection=ts;String[] names=new String[ts.length()];for(int i=0;i<names.length;i++)names[i]=ts.getJSONObject(i).getJSONObject("definition").getString("name")+" · v"+ts.getJSONObject(i).getInt("revision");a.dialog().setTitle(edit?"Endre turmal":"Velg turmal").setItems(names,(d,n)->{try{JSONObject t=selection.getJSONObject(n);if(edit)editor(t);else{if(!prefs().getString("pending","").isEmpty()){a.alert("Send ventende tur først. Utkastet beholdes.");return;}current=t;run=new JSONObject().put("id",UUID.randomUUID().toString()).put("revision",0);form(new JSONObject().put("course",courseName).put("values",new JSONObject()));}}catch(Exception e){a.alert(e.getMessage());}}).show();}catch(Exception e){a.alert(e.getMessage());}}
 void resume(){try{JSONObject draft=new JSONObject(prefs().getString("draft",""));current=draft.getJSONObject("template");run=draft.getJSONObject("run");form(draft.getJSONObject("payload"));JSONObject savedClocks=draft.optJSONObject("clocks");if(savedClocks!=null){Iterator<String> keys=savedClocks.keys();while(keys.hasNext()){String id=keys.next();clocks.put(id,savedClocks.getLong(id));}}}catch(Exception e){a.alert("Ingen lokalt utkast.");}}
 EditText field(LinearLayout panel,String label,String value,boolean number){panel.addView(a.text(label,15,a.TEXT));EditText e=new EditText(a);e.setTextColor(a.TEXT);e.setSingleLine(false);if(number)e.setInputType(2|4096|8192);e.setText(value);panel.addView(e);return e;}
 LinearLayout panel(){LinearLayout p=new LinearLayout(a);p.setOrientation(1);p.setPadding(22,12,22,12);return p;}
 ScrollView scroll(LinearLayout p){ScrollView s=new ScrollView(a);s.addView(p);return s;}
 void form(JSONObject payload)throws Exception{
  rendering=true;edits.clear();choices.clear();clocks.clear();LinearLayout p=panel();JSONObject values=payload.optJSONObject("values");if(values==null)values=new JSONObject();
  for(String key:new String[]{"driver","course","vehicle","date"}){EditText e=field(p,key.equals("driver")?"Elev":key.equals("course")?"Kurs":key.equals("vehicle")?"Bil":"Dato",payload.optString(key,key.equals("date")?new java.text.SimpleDateFormat("yyyy-MM-dd",Locale.ROOT).format(new Date()):""),false);edits.put("@"+key,e);}
  JSONArray ps=current.getJSONObject("definition").getJSONArray("parameters");p.addView(a.text("– = bevisst utelatt. Malversjon "+current.optInt("revision")+" beholdes på denne turen.",13,a.MUTED));
  for(int i=0;i<ps.length();i++){JSONObject def=ps.getJSONObject(i);String id=def.getString("id"),type=def.getString("type"),label=def.getString("label")+(def.optBoolean("required")?" *":"")+(def.optString("unit").isEmpty()?"":" ("+def.optString("unit")+")");Object v=values.opt(id);String val=v==null||v==JSONObject.NULL?"":String.valueOf(v);
   if(Arrays.asList("rating","boolean","choice").contains(type)){p.addView(a.text(label,15,a.TEXT));ArrayList<String> options=new ArrayList<>();options.add("");if(type.equals("rating"))options.addAll(Arrays.asList("Bra","Middels","Svak"));else if(type.equals("boolean")){options.addAll(Arrays.asList("Ja","Nei"));if(v instanceof Boolean)val=(Boolean)v?"Ja":"Nei";}else{JSONArray opts=def.getJSONArray("options");for(int j=0;j<opts.length();j++)options.add(opts.getString(j));}options.add("-");Spinner sp=new Spinner(a);sp.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,options));sp.setSelection(Math.max(0,options.indexOf(val)));choices.put(id,sp);p.addView(sp);sp.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> x){}public void onItemSelected(AdapterView<?> x,View view,int n,long row){persist();}});}
   else{EditText e=field(p,label,val,false);edits.put(id,e);if(type.equals("fuel"))e.setEnabled(false);if(type.equals("stopwatch"))a.button(p,"Start / stopp: "+def.getString("label"),()->{if(clocks.containsKey(id)){long start=clocks.remove(id);double old=0;try{old=Double.parseDouble(e.getText().toString().replace(',','.'));}catch(Exception ignored){}e.setText(String.format(Locale.ROOT,"%.2f",old+(Math.max(0,System.currentTimeMillis()-start))/60000.0));}else{clocks.put(id,System.currentTimeMillis());Toast.makeText(a,"Tidtakning startet",Toast.LENGTH_SHORT).show();}},false);}
  }
  TextWatcher watcher=new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){persist();}public void afterTextChanged(Editable e){}};for(EditText e:edits.values())e.addTextChangedListener(watcher);
  formDialog=a.dialog().setTitle(current.getJSONObject("definition").getString("name")).setView(scroll(p)).setNegativeButton("Lukk",(d,w)->persist()).setNeutralButton("Lagre uferdig",null).setPositiveButton("Lagre ferdig",null).create();formDialog.setOnShowListener(d->{formDialog.getButton(-3).setOnClickListener(vw->save(false));formDialog.getButton(-1).setOnClickListener(vw->save(true));});formDialog.setOnCancelListener(d->persist());formDialog.show();rendering=false;persist();
 }
 JSONObject capture()throws Exception{return capture(true);}
 JSONObject capture(boolean convert)throws Exception{JSONObject payload=new JSONObject().put("complete",false),values=new JSONObject();for(String key:new String[]{"driver","course","vehicle","date"})payload.put(key,edits.get("@"+key).getText().toString().trim());JSONArray ps=current.getJSONObject("definition").getJSONArray("parameters");for(int i=0;i<ps.length();i++){JSONObject def=ps.getJSONObject(i);String id=def.getString("id"),type=def.getString("type"),raw=choices.containsKey(id)?String.valueOf(choices.get(id).getSelectedItem()):edits.get(id).getText().toString().trim();if(type.equals("fuel"))continue;if(raw.isEmpty())values.put(id,JSONObject.NULL);else if(raw.equals("-"))values.put(id,"-");else if(Arrays.asList("number","integer","minutes","stopwatch").contains(type))values.put(id,convert?Double.parseDouble(raw.replace(',','.')):raw);else if(type.equals("boolean"))values.put(id,raw.equals("Ja"));else values.put(id,raw);}return payload.put("values",values);}
 void persist(){if(rendering||current==null||run==null||edits.isEmpty())return;try{calculateFuel();JSONObject payload=capture(false);prefs().edit().putString("draft",new JSONObject().put("template",current).put("run",run).put("payload",payload).put("clocks",new JSONObject(clocks)).toString()).commit();}catch(Exception ignored){}}
 void calculateFuel(){if(current==null)return;try{JSONArray ps=current.getJSONObject("definition").getJSONArray("parameters");for(int i=0;i<ps.length();i++){JSONObject def=ps.getJSONObject(i);if(!def.optString("type").equals("fuel"))continue;EditText e=edits.get(def.getString("id"));String value="";try{double km=Double.parseDouble(edits.get("km").getText().toString().replace(',','.')),liters=Double.parseDouble(edits.get("liters").getText().toString().replace(',','.'));if(km>0)value=String.format(Locale.ROOT,"%.3f",10*liters/km);}catch(Exception ignored){}if(e!=null&&!e.getText().toString().equals(value))e.setText(value);}}catch(Exception ignored){}}
 void save(boolean complete){if(busy)return;try{for(String id:new ArrayList<>(clocks.keySet())){long start=clocks.remove(id);EditText e=edits.get(id);double old=0;try{old=Double.parseDouble(e.getText().toString().replace(',','.'));}catch(Exception ignored){}e.setText(String.format(Locale.ROOT,"%.2f",old+(Math.max(0,System.currentTimeMillis()-start))/60000.0));}JSONObject payload=capture().put("complete",complete);JSONObject body=action("template_run_save").put("id",run.getString("id")).put("expected_revision",run.optInt("revision")).put("template_id",current.getString("id")).put("template_revision",current.getInt("revision")).put("payload",payload);String pending=prefs().getString("pending","");if(!pending.isEmpty()&&!new JSONObject(pending).getString("id").equals(run.getString("id")))throw new Exception("En annen tur venter på sending.");prefs().edit().putString("pending",body.toString()).commit();persist();sendPending();}catch(Exception e){a.alert("Kontroller feltene: "+e.getMessage());}}
 void sendPending(){try{JSONObject body=new JSONObject(prefs().getString("pending",""));request(body,r->{run=r.getJSONObject("run");prefs().edit().remove("pending").putString("last_saved",run.toString()).commit();persist();if(formDialog!=null)formDialog.dismiss();a.alert(r.optString("message")+"\nPoeng: "+run.getJSONObject("payload").optString("score","–"));});}catch(Exception e){a.alert("Ingen tur venter på sending.");}}
 void history(int offset,JSONArray all){try{request(action("template_runs").put("offset",offset),r->{JSONArray page=r.getJSONArray("runs");for(int i=0;i<page.length();i++)all.put(page.getJSONObject(i));ArrayList<String> labels=new ArrayList<>();for(int i=0;i<all.length();i++){JSONObject run=all.getJSONObject(i),p=run.getJSONObject("payload");labels.add(p.getString("driver")+" · "+p.getString("vehicle")+" · "+run.getJSONObject("snapshot").getString("name")+" · v"+run.getInt("template_revision")+" · "+(p.optBoolean("complete")?"Ferdig":"Uferdig"));}if(page.length()==100)labels.add("Hent flere …");a.dialog().setTitle("Registrerte parameterturer").setItems(labels.toArray(new String[0]),(d,n)->{try{if(n==all.length()){history(offset+100,all);return;}run=all.getJSONObject(n);current=new JSONObject().put("id",run.getString("template_id")).put("revision",run.getInt("template_revision")).put("definition",run.getJSONObject("snapshot"));form(run.getJSONObject("payload"));}catch(Exception e){a.alert(e.getMessage());}}).show();});}catch(Exception e){a.alert(e.getMessage());}}
 void bank(){try{JSONArray ps=catalog.getJSONArray("parameters");String[] labels=new String[ps.length()+1];labels[0]="Ny parameter";for(int i=0;i<ps.length();i++)labels[i+1]=ps.getJSONObject(i).getString("label");a.dialog().setTitle("Parameterbank").setItems(labels,(d,n)->{try{parameterEditor(n==0?null:ps.getJSONObject(n-1));}catch(Exception e){a.alert(e.getMessage());}}).show();}catch(Exception e){a.alert(e.getMessage());}}
 void parameterEditor(JSONObject old)throws Exception{
  JSONObject p=old==null?new JSONObject().put("id","p_"+UUID.randomUUID().toString().replace("-","")):new JSONObject(old.toString());LinearLayout panel=panel();EditText label=field(panel,"Navn",p.optString("label"),false),unit=field(panel,"Enhet",p.optString("unit"),false);String[] types={"number","integer","minutes","stopwatch","rating","boolean","choice","text","fuel"};Spinner type=new Spinner(a);type.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,new String[]{"Tall","Heltall","Minutter","Tidtakning","Vurdering","Ja / nei","Valgliste","Tekst","Beregnet forbruk per mil"}));type.setSelection(Math.max(0,Arrays.asList(types).indexOf(p.optString("type"))));panel.addView(type);EditText options=field(panel,"Valg adskilt med ;",join(p.optJSONArray("options")),false),weight=field(panel,"Poengvekt (0 = ingen)",p.optString("weight","0"),true),min=field(panel,"Min",p.isNull("min")?"":p.optString("min"),true),max=field(panel,"Maks",p.isNull("max")?"":p.optString("max"),true);Spinner direction=new Spinner(a);direction.setAdapter(new ArrayAdapter<String>(a,android.R.layout.simple_spinner_dropdown_item,new String[]{"Ingen poengretning","Lavere er bedre","Høyere er bedre"}));direction.setSelection(Math.max(0,Arrays.asList("none","low","high").indexOf(p.optString("direction"))));panel.addView(direction);CheckBox required=new CheckBox(a);required.setText("Obligatorisk");required.setTextColor(a.TEXT);required.setChecked(p.optBoolean("required"));panel.addView(required);CheckBox graph=new CheckBox(a);graph.setText("Vis i grafer");graph.setTextColor(a.TEXT);graph.setChecked(p.optBoolean("graph"));panel.addView(graph);
  AlertDialog dlg=a.dialog().setTitle("Parameter").setView(scroll(panel)).setNegativeButton("Avbryt",null).setPositiveButton("Lagre",null).create();dlg.setOnShowListener(d->dlg.getButton(-1).setOnClickListener(v->{try{JSONArray opts=new JSONArray();for(String s:options.getText().toString().split(";"))if(!s.trim().isEmpty())opts.put(s.trim());p.put("label",label.getText().toString()).put("unit",unit.getText().toString()).put("type",types[type.getSelectedItemPosition()]).put("options",opts).put("weight",Double.parseDouble(weight.getText().toString().replace(',','.'))).put("min",min.getText().toString().isEmpty()?JSONObject.NULL:Double.parseDouble(min.getText().toString().replace(',','.'))).put("max",max.getText().toString().isEmpty()?JSONObject.NULL:Double.parseDouble(max.getText().toString().replace(',','.'))).put("direction",new String[]{"none","low","high"}[direction.getSelectedItemPosition()]).put("required",required.isChecked()).put("graph",graph.isChecked());request(action("parameter_save").put("parameter",p),r->{dlg.dismiss();open();});}catch(Exception e){a.alert("Kontroller feltene.");}}));dlg.show();
 }
 String join(JSONArray array)throws Exception{if(array==null)return "";StringBuilder s=new StringBuilder();for(int i=0;i<array.length();i++){if(i>0)s.append(';');s.append(array.getString(i));}return s.toString();}
 void editor(JSONObject old){try{LinearLayout panel=panel();EditText name=field(panel,"Navn på turmal",old==null?"Ny egendefinert tur":old.getJSONObject("definition").getString("name"),false);JSONArray bank=catalog.getJSONArray("parameters"),selected=old==null?new JSONArray():old.getJSONObject("definition").getJSONArray("parameters");Map<String,JSONObject> chosen=new HashMap<>();for(int i=0;i<selected.length();i++)chosen.put(selected.getJSONObject(i).getString("id"),selected.getJSONObject(i));ArrayList<JSONObject> defs=new ArrayList<>();ArrayList<CheckBox> boxes=new ArrayList<>();for(int i=0;i<bank.length();i++){JSONObject p=bank.getJSONObject(i);if(chosen.containsKey(p.getString("id")))p=chosen.get(p.getString("id"));defs.add(p);CheckBox check=new CheckBox(a);check.setText(p.getString("label"));check.setTextColor(a.TEXT);check.setChecked(chosen.containsKey(p.getString("id")));boxes.add(check);panel.addView(check);final JSONObject parameter=p;a.button(panel,"Krav / poeng: "+p.getString("label"),()->templateField(parameter),false);}AlertDialog dlg=a.dialog().setTitle("Turmal · velg parametre").setView(scroll(panel)).setNegativeButton("Avbryt",null).setPositiveButton("Lagre versjon",null).create();dlg.setOnShowListener(d->dlg.getButton(-1).setOnClickListener(v->{try{JSONArray ps=new JSONArray();for(int i=0;i<boxes.size();i++)if(boxes.get(i).isChecked())ps.put(defs.get(i));JSONObject definition=new JSONObject().put("name",name.getText().toString()).put("base_trip",old==null?JSONObject.NULL:old.getJSONObject("definition").opt("base_trip")).put("parameters",ps);request(action("template_save").put("id",old==null?UUID.randomUUID().toString():old.getString("id")).put("expected_revision",old==null?0:old.getInt("revision")).put("definition",definition),r->{dlg.dismiss();open();});}catch(Exception e){a.alert(e.getMessage());}}));dlg.show();}catch(Exception e){a.alert(e.getMessage());}}
 void templateField(JSONObject p){LinearLayout panel=panel();CheckBox required=new CheckBox(a);required.setText("Obligatorisk");required.setTextColor(a.TEXT);required.setChecked(p.optBoolean("required"));panel.addView(required);EditText weight=field(panel,"Poengvekt",p.optString("weight","0"),true),direction=field(panel,"none / low / high",p.optString("direction","none"),false),min=field(panel,"Min",p.isNull("min")?"":p.optString("min"),true),max=field(panel,"Maks",p.isNull("max")?"":p.optString("max"),true);a.dialog().setTitle(p.optString("label")).setView(scroll(panel)).setNegativeButton("Avbryt",null).setPositiveButton("Bruk",(d,n)->{try{p.put("required",required.isChecked()).put("weight",Double.parseDouble(weight.getText().toString().replace(',','.'))).put("direction",direction.getText().toString()).put("min",min.getText().toString().isEmpty()?JSONObject.NULL:Double.parseDouble(min.getText().toString().replace(',','.'))).put("max",max.getText().toString().isEmpty()?JSONObject.NULL:Double.parseDouble(max.getText().toString().replace(',','.')));}catch(Exception e){a.alert("Kontroller tallene.");}}).show();}
 void course(){try{LinearLayout panel=panel();EditText name=field(panel,"Kursnavn","",false);JSONArray templates=catalog.getJSONArray("templates");ArrayList<CheckBox> boxes=new ArrayList<>();for(int i=0;i<templates.length();i++){CheckBox c=new CheckBox(a);c.setText(templates.getJSONObject(i).getJSONObject("definition").getString("name"));c.setTextColor(a.TEXT);boxes.add(c);panel.addView(c);}a.dialog().setTitle("Turmaler i kurs").setView(scroll(panel)).setNegativeButton("Avbryt",null).setPositiveButton("Lagre",(d,n)->{try{JSONArray ids=new JSONArray();for(int i=0;i<boxes.size();i++)if(boxes.get(i).isChecked())ids.put(templates.getJSONObject(i).getString("id"));request(action("template_course_save").put("name",name.getText().toString()).put("template_ids",ids),r->open());}catch(Exception e){a.alert(e.getMessage());}}).show();}catch(Exception e){a.alert(e.getMessage());}}
}
