package no.talappen.ysk;
import android.app.*;import android.content.*;import android.content.pm.*;import android.net.Uri;import android.os.Build;import android.provider.Settings;import android.widget.Toast;import org.json.*;import java.io.*;import java.net.*;import java.security.*;import java.util.*;
public class Updates {
 final MainActivity activity;JSONObject release;boolean busy=false,pendingInstall=false;long last=0;
 Updates(MainActivity a){activity=a;}
 long code(PackageInfo p){return Build.VERSION.SDK_INT>=28?p.getLongVersionCode():p.versionCode;}
 long installed()throws Exception{return code(activity.getPackageManager().getPackageInfo(activity.getPackageName(),0));}
 void automatic(){if(System.currentTimeMillis()-last>3600000&&!activity.getSharedPreferences("cloud",0).getString("url","").isEmpty())check(false);if(pendingInstall&&activity.getPackageManager().canRequestPackageInstalls()){pendingInstall=false;install();}}
 void check(boolean visible){if(busy)return;busy=true;last=System.currentTimeMillis();new Thread(()->{try{JSONObject result=Sync.admin(activity,new JSONObject().put("action","update_check").put("platform","android"));JSONObject r=result.optJSONObject("release");boolean newer=r!=null&&r.getLong("build")>installed();activity.runOnUiThread(()->{busy=false;release=newer?r:null;if(activity.isDestroyed())return;if(newer){String message="Kanal: "+result.optString("channel")+"\nVersjon "+r.optString("version")+" · bygg "+r.optInt("build")+"\n"+r.optString("published_at").split("T")[0]+"\n\n"+r.optString("notes");if(visible)new AlertDialog.Builder(activity).setTitle("Ny YSK-utgave").setMessage(message).setNegativeButton("Senere",null).setPositiveButton("Last ned",(d,w)->download()).show();else{activity.updateButton.setText("Ny versjon "+r.optString("version")+" · vis");}}else if(visible)activity.alert("Kanal: "+result.optString("channel")+"\n"+(r==null?"Ingen Android-utgave er publisert ennå.":"Du har siste tilgjengelige utgave."));});}catch(Exception e){activity.runOnUiThread(()->{busy=false;if(visible&&!activity.isDestroyed())activity.alert(e.getMessage());});}},"YSK-update-check").start();}
 byte[] signatures(PackageInfo p)throws Exception{android.content.pm.Signature[] ss=Build.VERSION.SDK_INT>=28?p.signingInfo.getApkContentsSigners():p.signatures;if(ss==null||ss.length!=1)throw new Exception("Uventet signatur i APK.");return ss[0].toByteArray();}
 void download(){if(busy||release==null)return;busy=true;String id=release.optString("id");activity.updateButton.setText("Laster ned og kontrollerer …");new Thread(()->{File partial=new File(activity.getCacheDir(),"update.part");try{JSONObject r=Sync.admin(activity,new JSONObject().put("action","download_update").put("platform","android").put("release_id",id)).getJSONObject("release");if(r.getLong("build")<=installed())throw new Exception("Denne utgaven er allerede installert.");JSONObject asset=r.getJSONObject("asset");URL url=new URL(asset.getString("url")),project=new URL(activity.getSharedPreferences("cloud",0).getString("url",""));if(!url.getProtocol().equals("https")||!url.getHost().equals(project.getHost())||url.getUserInfo()!=null||!url.getPath().startsWith("/storage/v1/object/sign/"))throw new Exception("Ugyldig nedlastingsadresse.");long expected=asset.getLong("size");if(expected<1||expected>100*1024*1024)throw new Exception("Ugyldig filstørrelse.");HttpURLConnection h=(HttpURLConnection)url.openConnection();h.setInstanceFollowRedirects(false);h.setConnectTimeout(15000);h.setReadTimeout(45000);MessageDigest digest=MessageDigest.getInstance("SHA-256");long total=0;try{if(h.getResponseCode()!=200)throw new Exception("Nedlasting feilet: HTTP "+h.getResponseCode());try(InputStream in=h.getInputStream();OutputStream out=new FileOutputStream(partial)){byte[] b=new byte[65536];int n;while((n=in.read(b))!=-1){total+=n;if(total>expected)throw new Exception("Filen er større enn oppgitt.");digest.update(b,0,n);out.write(b,0,n);}}}finally{h.disconnect();}StringBuilder hash=new StringBuilder();for(byte b:digest.digest())hash.append(String.format(Locale.ROOT,"%02x",b&255));if(total!=expected||!hash.toString().equals(asset.getString("sha256")))throw new Exception("Kontrollsum eller filstørrelse stemmer ikke.");int flags=Build.VERSION.SDK_INT>=28?PackageManager.GET_SIGNING_CERTIFICATES:PackageManager.GET_SIGNATURES;PackageManager pm=activity.getPackageManager();PackageInfo next=pm.getPackageArchiveInfo(partial.getPath(),flags),current=pm.getPackageInfo(activity.getPackageName(),flags);if(next==null||!activity.getPackageName().equals(next.packageName)||code(next)!=r.getLong("build")||!Arrays.equals(signatures(next),signatures(current)))throw new Exception("APK-versjonen eller signaturen stemmer ikke med appen.");File target=new File(activity.getCacheDir(),"update.apk");if(target.exists()&&!target.delete())throw new Exception("Kunne ikke erstatte nedlastingen.");if(!partial.renameTo(target))throw new Exception("Kunne ikke lagre oppdateringen.");activity.runOnUiThread(()->{busy=false;activity.updateButton.setText("Sjekk oppdateringer");if(!activity.isDestroyed())install();});}catch(Exception e){partial.delete();activity.runOnUiThread(()->{busy=false;activity.updateButton.setText("Sjekk oppdateringer");if(!activity.isDestroyed())activity.alert(e.getMessage());});}},"YSK-update-download").start();}
 void install(){if(!activity.getPackageManager().canRequestPackageInstalls()){new AlertDialog.Builder(activity).setTitle("Tillat YSK-oppdateringer").setMessage("Android trenger tillatelse til å installere oppdateringen fra YSK. Slå på tillatelsen og gå tilbake til appen.").setNegativeButton("Senere",null).setPositiveButton("Åpne innstillinger",(d,w)->{pendingInstall=true;activity.startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+activity.getPackageName())));}).show();return;}try{Intent i=new Intent(Intent.ACTION_VIEW).setDataAndType(Uri.parse("content://no.talappen.ysk.updates/update.apk"),"application/vnd.android.package-archive").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);activity.startActivity(i);}catch(Exception e){activity.alert("Kunne ikke åpne Androids installasjon: "+e.getMessage());}}
}
